### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by swasheck** [aptivate/python-tika#1]
Hi. Thanks for your work on this project. I'm probably doing something wrong here so feel free to let me know where I've missed something.
Here are my steps:

``` bash
virtualenv test_tika
cd test_tika
source bin/activate
pip install git+git://github.com/aptivate/jcc.git
pip install git+git://github.com/aptivate/python-tika.git
```

Up until this point I have no problems.

then: 

``` bash
python
```

``` python
import tika
```

renders :

``` bash

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/{PATH}/test_tika/lib/python2.7/site-packages/tika/__init__.py", line 2, in <module>
    import os, _tika
ImportError: dynamic module does not define init function (init_tika)
```

This is on Arch Linux - 3.3.2-1-ARCH #1 SMP PREEMPT x86_64

Python 2.7.3

**Comment by mlambir** [comment]
Where you able to resolve this issue? I'm getting the same error.
I'd appreciate any pointers in the right direction.

**Comment by Bengt** [comment]
I ran into this, too on Fedora 17 (kernel 3.5.3-1.fc17.x86_64) with Python 2.7.3 and Java 1.7.0 .

**Comment by Bengt** [comment]
@mlambir have a look at the pull request I referenced, it fixes this issue for me.

**Comment by JoeJasinski** [comment]
@Bengt, thanks for putting that repo together.  However, I'm using the branch from your repo, but also get the exact same error as above.  

``` python
>>> import tika
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jjasinski/Sites/testhaystack/lib/python2.7/site-packages/tika-1.1-py2.7-linux-i686.egg/tika/__init__.py", line 2, in <module>
    import os, _tika
ImportError: dynamic module does not define init function (init_tika)
```

**Comment by JoeJasinski** [comment]
For some more information on my development environment, if it will help:

Python Version: Python 2.7.3 
OS Version: Ubuntu Quantal 
JCC Setup: JCC_JDK="/usr/lib/jvm/java-7-openjdk-i386/"

Confirm JCC is installed

``` python
>>> import jcc
>>> jcc
<module 'jcc' from '/home/jjasinski/Sites/testhaystack/lib/python2.7/site-packages/jcc/__init__.pyc'>
>>> jcc.CLASSPATH
'/home/jjasinski/Sites/testhaystack/lib/python2.7/site-packages/jcc/classes'
```
